export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"
export const CART_SAVING_SHIPPING_ADDRESS = "CART_SAVING_SHIPPING_ADDRESS";
export const CART_SAVING_PAYMENT_METHOD = "CART_SAVING_PAYMENT_METHOD";